apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka-producer-deployment
  annotations:
    commitID: "c019d32f516e3f17d632bc743f3e8b131283f1cd"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-kafka-producer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-kafka-producer
    spec:
      containers:
        - name: api-kafka-producer
          image: 'xavelo/api-kafka-producer:c019d32f516e3f17d632bc743f3e8b131283f1cd'
          ports:
            - containerPort: 80
