apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka-producer-deployment
  annotations:
    commitID: "e290daa6746f37da8c443a3d154a6ac929425536"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-kafka-producer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-kafka-producer
    spec:
      containers:
        - name: api-kafka-producer
          image: 'xavelo/api-kafka-producer:e290daa6746f37da8c443a3d154a6ac929425536'
          ports:
            - containerPort: 80
